<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.1</version>
        <relativePath/>
    </parent>

    <groupId>ru.yarigo</groupId>
    <artifactId>media-conversion-service</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>Media Conversion Service</name>

    <properties>
        <java.version>25</java.version>
        <org.mapstruct.version>1.6.3</org.mapstruct.version>
        <spring.boot.version>4.0.1</spring.boot.version>
    </properties>

    <modules>
        <module>workspace-core</module>
        <module>workspace-spring</module>
        <module>storage-core</module>
        <module>storage-spring</module>
        <module>app</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- Spring Boot Starter для всех модулей -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter</artifactId>
                <version>${spring.boot.version}</version>
            </dependency>


        </dependencies>
    </dependencyManagement>

</project>